"""Central definitions and illustrated-lesson copy for public measures."""
from __future__ import annotations

from html import escape


def _metric(label: str, question: str, definition: str, example: str,
            steps: list[str], formula: str, unit: str, limitations: str,
            source: str, status: str) -> dict:
    return {"label": label, "question": question, "definition": definition,
            "example": example, "steps": steps, "formula": formula, "unit": unit,
            "limitations": limitations, "source": source, "status": status}


METRICS = {
    "effective_topics": _metric("Effective topics", "How many topics received meaningful attention?",
        "A diversity score translated back into an intuitive number of equally attended topics.",
        "Four equal topics score 4; one dominant topic scores close to 1.",
        ["Split words across paragraph topics", "Find each topic's speech share",
         "Calculate Shannon entropy", "Exponentiate the result"],
        "exp(−Σ pᵢ ln pᵢ)", "effective topics",
        "Depends on AI topic labels and paragraph boundaries.",
        "coverage_pressure.parquet", "confirmatory"),
    "depth_words": _metric("Topic depth", "How long did a topic hold the floor?",
        "The word length of a typical topic episode, giving long episodes proportionally more weight.",
        "A 50-word and 150-word episode produce (50²+150²)/(50+150)=125 words.",
        ["Find consecutive paragraphs carrying a topic", "Sum equivalent words in each run",
         "Weight longer runs by their length"],
        "Σ run_words² / Σ run_words", "equivalent words",
        "Multi-label paragraphs divide their words equally across topics.",
        "coverage_pressure.parquet", "confirmatory"),
    "leading_topic_share": _metric("Leading-topic share", "How concentrated was the speech?",
        "The fraction of topic exposure assigned to the speech's largest topic.",
        "If the largest topic receives 300 of 1,000 equivalent words, the share is 30%.",
        ["Find topic exposures", "Choose the largest", "Divide by all exposed words"],
        "max(topic words) / all topic words", "share",
        "A low value can mean broad coverage or noisy labeling.",
        "coverage_pressure.parquet", "secondary"),
    "adjacent_similarity": _metric("Adjacent-paragraph similarity", "Did neighboring paragraphs stay on the same subjects?",
        "Average Jaccard overlap between the topic sets of neighboring paragraphs.",
        "Topics {A,B} beside {B,C} overlap by 1 of 3, or 0.33.",
        ["Compare neighboring topic sets", "Divide overlap by union", "Average pairs"],
        "|A∩B| / |A∪B|", "Jaccard similarity",
        "Paragraph segmentation changes which pairs are neighbors.",
        "coverage_pressure.parquet", "secondary"),
    "rate_10k": _metric("Rate per 10,000 words", "How often does wording appear after allowing for length?",
        "A count divided by all words and scaled to a same-sized 10,000-word container.",
        "Five mentions in 10,000 words equals 5 per 10,000.",
        ["Count included words", "Count all words", "Divide and multiply by 10,000"],
        "count / words × 10,000", "mentions per 10,000 words",
        "Words can carry different meanings in context.", "speech_markers.parquet", "descriptive"),
    "explore_centered_lexical_rate": _metric(
        "Centered five-year lexical rate",
        "How often does one exact form or audited word family appear around each corpus year?",
        "Exact or grouped matches and all indexed source-document words are summed from center year minus two through center year plus two; the match total is divided by the word total and scaled to 10,000 only when the window exceeds 20,000 indexed words.",
        "Forty matches among 80,000 indexed words in a centered five-year window equals 5 uses per 10,000 words.",
        [
            "Tokenize every complete source-document transcript with the Explore word tokenizer",
            "For grouped series, replace forms only through the frozen audited word-family map",
            "Sum matches and indexed words over the five calendar years centered on the displayed year",
            "Publish only when the window contains more than 20,000 indexed words",
            "Divide matches by words and multiply by 10,000",
        ],
        "Σ matches(center−2…center+2) / Σ indexed words(center−2…center+2) × 10,000",
        "uses per 10,000 indexed words",
        "A match does not establish meaning, intent, endorsement, or context. Grouped forms follow an audited deterministic algorithm and do not imply universal linguistic equivalence; sparse windows are unknown rather than zero.",
        "speeches.parquet + word_families.json",
        "descriptive",
    ),
    "paragraph_share": _metric("Share of paragraphs", "How much of the record carries a label?",
        "The number of labeled paragraphs divided by every paragraph in the selected record.",
        "Twenty labeled paragraphs among 100 total paragraphs is 20%.",
        ["Count paragraphs carrying the label", "Count every eligible paragraph",
         "Divide the labeled count by the total"],
        "labeled paragraphs / eligible paragraphs", "percent of paragraphs",
        "Paragraphs vary greatly in length, and AI labels can disagree.",
        "paragraph_annotations.parquet", "exploratory AI descriptive"),
    "era_distinctive_reference": _metric(
        "Era-distinctive reference",
        "Which normalized names are unusually concentrated in one Story era?",
        "Positive Jeffreys-smoothed paragraph log odds compare one era with the other eight on eligible speaker-audited paragraphs.",
        "A name supported by six paragraphs in an era and none elsewhere can rank above a more common name that is also widespread across other eras.",
        [
            "Count each normalized entity once per eligible paragraph",
            "Keep names supported by at least five paragraphs and two source documents",
            "Apply a 0.5 Jeffreys prior to present and absent counts in the era and comparison corpus",
            "Rank positive log odds by score, era paragraphs, source documents, then normalized name",
        ],
        "log((era name paragraphs + 0.5)/(era other paragraphs + 0.5)) − log((other-era name paragraphs + 0.5)/(other-era other paragraphs + 0.5))",
        "speaker-audited paragraph log odds",
        "AI + NER and AI only describe source agreement, not historical validation or confidence. Distinctive does not mean important, representative, prevalent, endorsed, or historically significant.",
        "reference_entities/era_distinctive_v1.parquet + speaker_views/paragraph_view_v1.parquet",
        "exploratory descriptive",
    ),
    "reference_type_presence": _metric(
        "Reference-type paragraph presence",
        "What kinds of named actors and places enter an era's presidential record?",
        "Distinct eligible paragraphs actually attributed to a president and carrying at least one primary-AI-backed entity of the named type, divided by every eligible actual-president paragraph in the Story era.",
        "If 100 of 500 eligible actual-president paragraphs name at least one person, person presence is 20%.",
        [
            "Use every eligible actual-president paragraph in the era as the denominator",
            "Keep primary-AI-backed people, institutions, groups, and nations or places",
            "Count a paragraph once per entity type even when it names several entities of that type",
            "Divide each type's distinct paragraph count by the complete era denominator",
        ],
        "distinct paragraphs carrying entity type / all eligible actual-president paragraphs",
        "share of speaker-audited paragraphs",
        "Entity types come from the primary AI and can overlap within a paragraph, so the four shares are non-additive. NER source agreement does not establish confidence, stance, or historical importance.",
        "reference_entities/entity_mentions_v1.parquet + speaker_views/paragraph_view_v1.parquet",
        "exploratory descriptive",
    ),
    "actual_speaker_topic_presence": _metric(
        "Actual-speaker topic presence",
        "What share of one president's eligible speaker-audited paragraph record carries an AI-assigned topic?",
        "Distinct eligible paragraphs actually attributed to the president and carrying the canonical topic, divided by every eligible paragraph attributed to that president in the complete corpus or one accepted Story era. Topic-free eligible paragraphs remain in the denominator.",
        "Twenty topic-bearing paragraphs among 100 eligible paragraphs actually attributed to the president is a 20% speaker-paragraph share.",
        [
            "Use only actual-president paragraphs marked eligible by the accepted speaker foundation",
            "Count each normalized topic once per paragraph and derive each Level 1 parent once",
            "Keep topic-free eligible paragraphs in the president denominator",
            "Compute corpus-wide and accepted Story-era scopes without recomputing eras",
            "Label presidents with 1–4 eligible actual-speaker appearances thin and require five appearances for supported status",
        ],
        "topic paragraphs attributed to president / all eligible paragraphs attributed to president in scope",
        "speaker-audited paragraph share",
        "Multi-label shares are non-additive and may sum above 100%. AI topic presence is descriptive and non-causal; it is not confidence, intent, importance, influence, success, or representation of the public or presidency as a whole. Supported edges additionally require five topic paragraphs and two topic-bearing appearances.",
        "speaker_topic_network/edges_v1.parquet",
        "exploratory AI descriptive",
    ),
    "actual_speaker_topic_contribution": _metric(
        "Actual-speaker topic contribution",
        "What share of a scope's eligible paragraph evidence assigned to a topic comes from one actual president speaker?",
        "Distinct eligible topic-bearing paragraphs actually attributed to the president, divided by all eligible paragraphs carrying that canonical topic across actual president speakers in the complete corpus or one accepted Story era.",
        "If 30 of a scope's 120 eligible paragraphs carrying a topic are actually attributed to one president, the topic-contribution share is 25%.",
        [
            "Use the accepted actual-speaker population and keyed topic memberships",
            "Count every distinct normalized topic presence fully in multi-label paragraphs",
            "Divide the president's topic paragraphs by all scope paragraphs carrying that topic",
            "Retain explicit paragraph and actual-speaker appearance counts",
            "Mark 1–4-appearance presidents and under-threshold edges as thin",
        ],
        "topic paragraphs attributed to president / all eligible paragraphs carrying topic in scope",
        "share of eligible topic-bearing paragraphs",
        "Multi-label topic shares are non-additive and may sum above 100%; topic-free paragraphs create no topic contribution but remain in scope corpus denominators. The measure is descriptive and non-causal, not confidence, intent, importance, influence, success, or representation of the public or presidency as a whole.",
        "speaker_topic_network/edges_v1.parquet",
        "exploratory AI descriptive",
    ),
    "actual_speaker_invocation_paragraph_count": _metric(
        "Actual-speaker invocation paragraph count",
        "In how many distinct eligible paragraphs did one actual president speaker invoke a named former president?",
        "The count of distinct keyed paragraphs attributed to the source president that contain at least one accepted invocation row for the target president.",
        "Three accepted mentions of the same former president in two keyed paragraphs produce a displayed bar value of two paragraphs.",
        [
            "Validate accepted invocation evidence against its governed candidates and classifier replay",
            "Overlay each keyed paragraph with the accepted actual-speaker attribution",
            "Keep resolved, eligible, former-president, non-self rows",
            "Count each distinct source document and paragraph key once for an actual-speaker to target edge",
        ],
        "count distinct (doc_name, para_idx) by actual speaker → named former president",
        "eligible reference paragraphs",
        "The count describes qualifying named references in this corpus, not historical contact, influence, endorsement, rivalry, importance, or a rate adjusted for corpus size. Target status follows corpus speech dates rather than an independent legal-term calendar.",
        "invocations_v2 accepted evidence + speaker_views/paragraph_view_v1.parquet",
        "exploratory AI descriptive",
    ),
    "legacy_issue_attention": _metric(
        "Legacy issue attention",
        "What share of a president's source-document paragraphs carries one displayed CorEx issue?",
        "Boolean-positive paragraphs for the displayed CorEx issue divided by every corpus paragraph in speeches owned by that president.",
        "Twenty positive paragraphs among 100 source-document paragraphs is 20% legacy issue attention.",
        [
            "Join paragraphs to speeches by document identity",
            "Group the joined paragraphs by source-document president owner",
            "Count Boolean-positive paragraphs for the displayed issue",
            "Divide by every source-document paragraph owned by that president",
        ],
        "issue-positive source-document paragraphs / all source-document paragraphs",
        "percent of source-document paragraphs",
        "CorEx issues are multi-label and methodologically distinct from actual-speaker AI topics. Source-document ownership is not speaker attribution, and the measure is descriptive rather than causal.",
        "issues_president.parquet + paragraph_issues.parquet",
        "exploratory descriptive",
    ),
    "president_percentile": _metric("President percentile", "Where does a president sit among comparable records?",
        "The percentage of eligible presidents whose measured value is at or below this one.",
        "The 80th percentile means the value is at least as high as about 80% of eligible presidents.",
        ["Calculate the same measure for every eligible president",
         "Exclude records below the five-speech precision floor", "Order the values",
         "Report the president's relative position"],
        "rank among eligible presidents / number eligible", "percentile from 0 to 100",
        "A percentile is a relative position, not an absolute amount or a quality ranking.",
        "president profile payload", "descriptive"),
    "era_relative": _metric("Era-relative difference", "What did a president emphasize more than contemporaries?",
        "A president's rate minus the average rate among nearby presidents.",
        "12% versus an 8% era baseline is +4 percentage points.",
        ["Estimate the president", "Estimate the contemporary baseline", "Subtract baseline"],
        "observed − era baseline", "percentage points",
        "The answer depends on the chosen comparison window.", "issues_president.parquet", "descriptive"),
    "confidence_interval": _metric("Confidence interval", "Which estimates remain plausible under repeated samples?",
        "A range produced by repeatedly resampling whole speeches.",
        "A 7% estimate with a 4–10% interval says repeat samples often land in that range.",
        ["Resample speeches", "Recalculate the estimate", "Keep the middle 95%"],
        "bootstrap quantiles 2.5% and 97.5%", "measure's native unit",
        "It is not a 95% probability that this one fixed interval contains truth.",
        "bands.parquet", "frequentist"),
    "reading_level": _metric("Flesch–Kincaid grade level", "How difficult is the sentence structure and vocabulary?",
        "An estimate of the U.S. school grade needed to read a passage, based on sentence length and syllables per word.",
        "A score of 8 suggests eighth-grade sentence and word complexity; it does not mean only eighth graders can understand it.",
        ["Count words and sentences", "Estimate syllables in each word",
         "Calculate average sentence length and syllables per word",
         "Combine them on the Flesch–Kincaid grade scale"],
        "0.39(words/sentences) + 11.8(syllables/words) − 15.59", "U.S. grade level",
        "It estimates surface difficulty, not accuracy, eloquence, intelligence, or the complexity of the ideas. Names, quotations, and formulaic legal language can move the score.",
        "speech_stats.parquet", "descriptive"),
    "primary_medium": _metric(
        "Primary medium assigned in the corpus",
        "What single communication form did the AI taxonomy assign to each speech?",
        "A mutually exclusive primary-form label used to describe this corpus's composition.",
        "A televised spoken address receives one primary label here, not both a spoken and broadcast count.",
        ["Read the speech title and opening context", "Assign one declared medium label",
         "Count the labels within the displayed period"],
        "speeches with label / corpus speeches in period", "share of corpus speeches",
        "It is not a complete inventory of delivery channels. Spoken addresses may also have "
        "been broadcast, and the label is an AI factual classification rather than archival metadata.",
        "llm_annotations/speech_annotations.parquet", "descriptive"),
    "assigned_audience": _metric(
        "Primary audience assigned in the corpus",
        "Who did the speech's framing most directly address?",
        "A mutually exclusive primary-audience label assigned from the speech title and opening context.",
        "An annual message addressed to Congress receives the Congress label even if newspapers later carried it to the public.",
        ["Read the title and opening context", "Assign one declared audience label",
         "Count labels within the displayed period"],
        "speeches with label / corpus speeches in period", "share of corpus speeches",
        "It does not inventory indirect audiences, circulation, reception, or rebroadcasting.",
        "llm_annotations/speech_annotations.parquet", "descriptive"),
    "proposal_values": _metric(
        "Proposal and values stance",
        "Is a paragraph proposing action, invoking values, doing both, or doing neither?",
        "A mutually exclusive projection of the frozen proposal/values paragraph judgment.",
        "A paragraph assigned both proposal and values appears in the mixed category once.",
        ["Join paragraphs to annotations by document and paragraph index",
         "Project both to mixed", "Divide each category count by all era paragraphs"],
        "category paragraphs / all era paragraphs", "percent of paragraphs",
        "The categories do not measure enactment, sincerity, persuasion, or policy quality.",
        "llm_annotations/paragraph_annotations.parquet", "exploratory AI descriptive"),
    "enemy_identity": _metric(
        "Adversarial framing and named adversaries",
        "Who or what is framed as an opponent, and how often does conflict framing appear?",
        "AI labels for enemy naming, zero-sum framing, partisan attack, and adversarial entity mentions.",
        "China and Democrats can both appear in one era's ranked list when distinct paragraphs frame them adversarially.",
        ["Join annotations on keyed paragraphs", "Canonicalize only declared aliases",
         "Count distinct supporting paragraphs", "Report rates and raw labels together"],
        "flagged paragraphs / eligible paragraphs", "percent of paragraphs",
        "Context errors remain possible; a name in the list is not a judgment that it was a legitimate enemy.",
        "combat/combativeness.parquet + llm_annotations/paragraph_entities.parquet",
        "exploratory AI descriptive"),
    "enemy_category_share": _metric(
        "Category of named adversary",
        "What kind of entity is framed as an adversary in each era?",
        "The share of extracted adversarial entity mentions assigned to nation, group, person, institution, or other.",
        "If 60 of 100 adversarial entity mentions are nations, the nation category is 60%.",
        ["Keep entity mentions with adversarial stance", "Assign the frozen entity type",
         "Count mentions by type within an era", "Divide by all adversarial entity mentions in that era"],
        "category adversarial mentions / all adversarial mentions", "percent of adversarial mentions",
        "Entity extraction and type labels can be wrong; the distribution excludes conflict wording without an extracted adversarial entity.",
        "combat/target_mix_by_era_speaker_audited_v1.parquet",
        "exploratory AI descriptive"),
    "temporal_orientation": _metric(
        "Future and nostalgia vocabulary",
        "How often does presidential wording point toward tomorrow or recover yesterday?",
        "Declared word families for forward-looking and backward-looking temporal appeal.",
        "A speech can contain both families and therefore score highly on both.",
        ["Match declared word families", "Count all eligible words",
         "Scale each family to 10,000 words"],
        "family count / words × 10,000", "mentions per 10,000 words",
        "A match cannot establish whether a promise is feasible or a memory is accurate.",
        "register/trends.parquet", "descriptive"),
    "temporal_portrait": _metric(
        "Temporal appeals by president and over time",
        "How often does presidential wording invoke tomorrow or recovery of yesterday?",
        "Future and nostalgia matches per 10,000 marker words position each president and form two separate trailing four-year rolling averages of annual rates.",
        "A president at 8 future and 5 nostalgia matches per 10,000 words sits at (8, 5); a timeline point averages the four annual rates ending in its displayed year.",
        ["Pool every available corpus speech assigned to the president",
         "Count future and nostalgia families and divide each by marker words",
         "For the timeline, calculate each annual rate and average four consecutive years",
         "Require coverage in all four years and at least 10,000 total window words"],
        "future rate = future/words × 10,000; nostalgia rate = nostalgia/words × 10,000",
        "matches per 10,000 marker words",
        "Each year receives equal weight in the rolling average even when its speech volume differs. Dictionary matches do not establish intent, feasibility, or historical accuracy; genre, quotations, other speakers, and uneven coverage can change the rates.",
        "speech_markers.parquet + speeches.parquet", "descriptive"),
    "hope_doom_ratio": _metric(
        "Hope divided by doom",
        "How much hope vocabulary appears for each doom term in one supported time window?",
        "The aggregate NRC hope count divided by the aggregate doom-family count in a centered five-year window.",
        "A value of 80 means eighty NRC hope matches for each doom-family match in that window.",
        ["Sum NRC hope, doom, and words within the window", "Require at least 20,000 words",
         "Suppress a zero doom denominator", "Divide aggregate counts"],
        "Σ NRC hope matches / Σ doom matches", "hope matches per doom match",
        "The two dictionaries differ greatly in breadth. A ratio can rise when hope increases or doom falls, so absolute rates remain in tooltips.",
        "speech_markers.parquet", "descriptive"),
    "uncertainty_envelope": _metric("Uncertainty envelope", "How much uncertainty comes from sampling and AI disagreement?",
        "The displayed interval width is the upper bound minus the lower bound in percentage points; a combined interval expands sampling variation by measured annotator disagreement.",
        "A sampling-only 4–8% range is 4 percentage points wide; a 3–10% combined range is 7 points wide.",
        ["Bootstrap speeches with source bounds stored as 0–1 shares", "Measure paired-model disagreement where applicable", "Combine the two components", "Subtract lower from upper and multiply by 100 for the displayed width"],
        "displayed width = (upper share − lower share) × 100 percentage points", "percentage-point interval width (source bounds stored as 0–1 shares)",
        "Disagreement measured on a sample is assumed to transfer to the corpus.",
        "data/quality/uncertainty_decomposition.csv (derived from bands.parquet)", "quality-aware descriptive"),
    "p_value": _metric("No-change surprise rate", "How surprising is this under a no-change model?",
        "The share of no-change repetitions at least as extreme as the observed result.",
        "4.2% means about four of 100 no-change repetitions were this extreme—not a 4.2% chance the finding is random.",
        ["Specify the no-change model", "Repeat the test", "Count equally or more extreme results"],
        "(extreme draws + 1) / (draws + 1)", "percent",
        "It is not the probability that a finding is random, real, or important.",
        "inference_receipts.parquet", "frequentist"),
    "kappa": _metric("Cohen’s κ", "Do two labelers agree beyond easy chance agreement?",
        "Agreement corrected for the labels each model uses most often.",
        "Two models saying 'no' on nearly everything can have high raw agreement but modest κ.",
        ["Build a confusion matrix", "Measure observed agreement",
         "Estimate agreement from each model's label rates", "Correct the observed value"],
        "(observed − expected) / (1 − expected)", "−1 to 1",
        "Rare labels can depress κ even when most rows match.",
        "agreement_v1.parquet", "quality audit"),
    "network_edge": _metric("Network edge", "Why are two nodes connected?",
        "An edge aggregates source records shared by the two nodes.",
        "Twenty paragraphs and eight speeches carrying two topics create one supported edge.",
        ["Find shared paragraphs", "Count distinct speeches", "Calculate Jaccard and lift"],
        "edge weight = shared evidence", "records or similarity",
        "Thresholds hide weak evidence but do not make visible edges causal.",
        "network_atlas.json", "exploratory"),
    "topic_lifecycle": _metric("Topic lifecycle", "When did an issue appear, disappear, persist, or return?",
        "A classification based on substantive years and long internal gaps.",
        "A topic absent for 35 years and later returning is marked revived.",
        ["Build a smoothed attention curve", "Apply the substantive threshold",
         "Find first, last, and long gaps", "Assign born/died/persistent/revived"],
        "thresholded attention timeline", "lifecycle class",
        "Boundary years depend on corpus coverage and the declared threshold.",
        "topic_lifecycles.parquet", "exploratory"),
    "legal_procedural": _metric("Legal and procedural vocabulary", "How often did presidents use formal governing terms?",
        "A rate for public wording such as act, bill, treaty, section, and appropriation.",
        "It measures what speeches say, not how competently government operated.",
        ["Match the declared word list", "Count all speech words", "Report per 10,000"],
        "included terms / words × 10,000", "mentions per 10,000 words",
        "It does not measure competence, productivity, policy depth, or enacted law.",
        "speech_markers.parquet", "descriptive"),
    "legal_hype_ratio": _metric(
        "Legal/procedural vocabulary divided by hype",
        "How many legal or procedural matches appear for each hype match in one supported time window?",
        "The aggregate legal/procedural count divided by the aggregate hype count in a centered five-year window.",
        "A value of 2 means two legal/procedural dictionary matches per hype dictionary match.",
        ["Sum both dictionaries and words within the window", "Require at least 20,000 words",
         "Suppress a zero hype denominator", "Divide legal/procedural matches by hype matches"],
        "Σ legal/procedural matches / Σ hype matches",
        "legal/procedural matches per hype match",
        "The dictionaries differ in breadth. The ratio can rise when legal/procedural wording increases or hype falls, so both rates remain available in exact details.",
        "speech_markers.parquet", "descriptive"),
    "hype_doom": _metric("Hype and doom vocabulary", "How often did speeches use extreme positive or negative wording?",
        "Declared word families for superlative praise and catastrophic decline.",
        "greatest is included in hype; difficult is not automatically doom.",
        ["Match included word families", "Keep hype and doom separate", "Scale per 10,000 words"],
        "family count / words × 10,000", "mentions per 10,000 words",
        "Dictionary matches cannot fully resolve sarcasm or quoted speech.",
        "speech_markers.parquet", "descriptive"),
    "similarity": _metric("Cosine similarity",
        "Which presidents align inside one named, finite feature set?",
        "The angle between two vectors built from declared inputs such as 50 topic shares "
        "or eight rhetorical measures.",
        "Two presidents can score highly on AI topics and much lower on rhetoric; neither "
        "score is an overall likeness.",
        ["Choose one declared feature space", "Standardize unlike rhetorical units when needed",
         "Normalize vector lengths", "Take the dot product"],
        "A·B / (||A|| ||B||)", "−1 to 1",
        "A high score is resemblance within the named inputs, not influence, ideology, "
        "agreement, or general similarity.",
        "president_edges.parquet", "exploratory"),
    "annotation_population_lineage": _metric(
        "Annotation population lineage",
        "Which records enter each annotation and evaluation population?",
        "A keyed ledger carries every reported population from its source corpus through ownership correction, eligibility, annotation, and paired evaluation.",
        "The paired-model population is a subset of the sampled population, not a substitute for the full eligible corpus.",
        ["Name the source population", "Apply each declared inclusion or exclusion rule",
         "Validate keyed one-to-one transitions", "Publish counts and downstream consumers"],
        "population after step = population before step − declared exclusions + declared additions",
        "documents, speeches, or paragraphs at the named grain",
        "Counts at different grains are not interchangeable, and lineage establishes scope rather than validity.",
        "data/quality/population_ledger.csv + data/quality/manifest_v2.json",
        "quality audit",
    ),
    "annotation_evidence_visibility": _metric(
        "Annotation evidence visibility",
        "Can a published judgment be traced back to governed evidence?",
        "A provenance receipt links a claim to its population, method, uncertainty, artifact, status, limitation, and downstream use.",
        "A chart value is inspectable when its source artifact and population contract are both named beside it.",
        ["Identify the public claim", "Name its population and unit",
         "Link the governed artifact and method", "Declare uncertainty, status, and limitation"],
        "receipt = claim + population + method + uncertainty + artifact + status + limitation + use",
        "provenance fields",
        "A complete receipt improves auditability but does not prove that a model judgment is historically valid.",
        "data/quality/manifest_v2.json",
        "quality audit",
    ),
    "annotation_pipeline_lineage": _metric(
        "Annotation pipeline lineage",
        "Which governed processing stages connect source text to a public judgment?",
        "An ordered provenance flow names corpus segmentation, taxonomy discovery and freeze, masked judgment, normalization, and independent reproducibility audit as distinct stages.",
        "A paragraph can be traced from its source key through a frozen prompt and normalized output without treating second-model availability as completion of the whole pipeline.",
        ["Identify the source corpus and semantic key", "Record discovery and taxonomy-freeze receipts",
         "Record masked judgment prompt and run identity", "Normalize outputs", "Link the separate reproducibility audit"],
        "source key → discovery/freeze → masked judgment → normalization → audit receipt",
        "ordered governed processing stages",
        "Pipeline traceability does not establish human validity, and the final audit stage can be incomplete without invalidating primary annotations.",
        "data/llm_annotations/manifests/*.json + data/quality/manifest_v2.json",
        "quality audit",
    ),
    "annotation_processing_completion": _metric(
        "Paired-evaluation availability",
        "How much of the planned second-model sample has a keyed paired judgment?",
        "Completed keyed paragraph pairs divided by every paragraph selected for paired evaluation; missing records stay explicit.",
        "A missing second judgment reduces paired-evaluation availability but is not recoded as a negative label.",
        ["Load the deterministic sample ledger", "Validate unique paragraph keys",
         "Match completed second-model rows by key", "Report completed and missing counts by speech and era"],
        "completed paired paragraph keys / selected paragraph keys",
        "percent of sampled paragraphs",
        "High completion does not establish cross-model agreement, human validity, or representative corpus coverage.",
        "data/quality/population_ledger.csv + data/quality/second_model_by_speech.csv",
        "quality audit",
    ),
    "intermodel_agreement_overall": _metric(
        "Overall cross-model reproducibility",
        "How consistently do two model passes apply the same frozen rubric?",
        "Field-appropriate agreement measures summarize the complete keyed paired-evaluation population, with prevalence and support shown alongside them.",
        "Binary fields use κ and raw agreement, while multi-label fields use set overlap; these values belong in separate metric families.",
        ["Restrict to completed keyed pairs", "Normalize with the governed taxonomy",
         "Choose a measure appropriate to the field", "Publish prevalence, support, and a speech-clustered interval"],
        "agreement measure appropriate to field over all completed pairs",
        "agreement, overlap, or exact-match scale",
        "The second model is another instrument, not human ground truth; measures from different families must not be ranked as one league table.",
        "agreement_v1.parquet + data/quality/agreement_by_field_and_era.csv",
        "cross-model reproducibility",
    ),
    "intermodel_agreement_by_story_era": _metric(
        "Cross-model reproducibility by Story era",
        "Does rubric reproducibility vary across the governed Story eras?",
        "Field-appropriate agreement is recomputed within the nine governed chronological Story eras, with paragraph and speech support retained.",
        "A lower interval in one era can reflect fewer speeches, different prevalence, or harder language rather than a proven historical trend.",
        ["Assign each pair from its speech year to a governed Story era", "Preserve governed chronological era order",
         "Compute the field's agreement measure", "Cluster resampling by speech and report support"],
        "agreement(field | governed Story era)",
        "agreement, overlap, or exact-match scale by Story era",
        "Story eras are editorial periods rather than random samples, and their estimates can be unstable at low support.",
        "agreement_v1.parquet + data/quality/agreement_by_field_and_era.csv",
        "cross-model reproducibility",
    ),
    "entity_name_and_stance_reproducibility": _metric(
        "Entity detection-to-stance reproducibility",
        "Do two model passes find the same normalized names and then assign the same stance?",
        "A funnel first measures matched normalized name instances among all detected instances, then measures stance agreement only among matched names; paragraph Jaccard is reported under both declared empty-set treatments.",
        "Both-empty paragraphs increase all-pair Jaccard but do not contribute a detected name to the stance stage.",
        ["Normalize entity names with the governed function", "Pair detections by paragraph and name",
         "Count matched detections among the detection union", "Evaluate stance only on matches and publish both Jaccard denominators"],
        "name match = matched instances / union instances; stance = matching stance / matched instances",
        "percent of entity instances or paragraph-level Jaccard",
        "Case normalization is not complete historical alias resolution, and model-to-model reproducibility is not human validity.",
        "data/quality/entity_name_agreement.csv + data/quality/entity_stance_matches.csv",
        "cross-model reproducibility",
    ),
    "coarse_pos_share": _metric(
        "Coarse part-of-speech share",
        "What share of tagged alphabetic tokens receives each universal part-of-speech label?",
        "Deterministic spaCy token counts are divided by all alphabetic tokens at the declared speech or aggregate grain.",
        "A 12% pronoun share means 12 of every 100 tagged alphabetic tokens were classified as pronouns.",
        ["Fingerprint the complete source corpus", "Tag each speech with the pinned spaCy model",
         "Keep alphabetic tokens", "Count universal tags and divide by the declared token denominator"],
        "tokens with POS tag / all tagged alphabetic tokens",
        "percent of tagged alphabetic tokens",
        "Historical spelling, transcription, quotations, genre, and model errors can move the shares; they do not identify syntax or causality.",
        "data/grammar/speech_pos.parquet + data/grammar/manifest.json",
        "derived feature engineering",
    ),
    "exact_agreement": _metric(
        "Exact agreement",
        "How often are two normalized judgments identical?",
        "The share of paired records whose complete normalized value is identical across the two model passes.",
        "For a multi-label field, {A, B} and {B, A} match after normalization, while {A} and {A, B} do not.",
        ["Normalize both values", "Compare each keyed pair", "Count identical pairs",
         "Divide by every eligible completed pair"],
        "identical normalized pairs / eligible completed pairs",
        "percent of pairs",
        "Exact agreement can be dominated by common negatives and does not correct for chance or partial set overlap.",
        "agreement_v1.parquet",
        "cross-model reproducibility",
    ),
    "jaccard": _metric(
        "Jaccard set overlap",
        "How much of the combined set did two judgments share?",
        "Intersection size divided by union size, with the treatment of two empty sets declared explicitly.",
        "Topic sets {A, B} and {B, C} share one of three combined labels, for Jaccard 0.33.",
        ["Normalize both sets", "Count their intersection", "Count their union",
         "Divide and state whether both-empty pairs are included"],
        "|A ∩ B| / |A ∪ B|",
        "0–1 overlap",
        "Averages depend materially on whether both-empty pairs are included and do not identify which model is correct.",
        "agreement_v1.parquet",
        "cross-model reproducibility",
    ),
    "era_annual_abruptness": _metric(
        "Annual transition abruptness",
        "Where do adjacent historical windows differ most across the governed feature system?",
        "The Euclidean magnitude of right-minus-left standardized axis changes is ranked separately for symmetric four- and eight-year windows, then their within-window percentiles are averaged.",
        "Several adjacent high-scoring years form one annual transition mountain rather than several independent boundaries.",
        ["Build governed feature vectors on both sides of every eligible year", "Scale each right-minus-left axis difference by that axis's population standard deviation across governed 8-year-bin fingerprints",
         "Measure the right-minus-left vector magnitude", "Combine four- and eight-year percentile ranks"],
        "consensus = (percentile(rank₄) + percentile(rank₈)) / 2",
        "0–1 consensus abruptness percentile",
        "Abruptness diagnoses change but cannot choose a historically meaningful boundary by itself; overlapping windows are dependent.",
        "era_boundaries/consensus_scores.parquet + era_boundaries/sliding_scores.parquet",
        "derived sensitivity diagnostic",
    ),
    "era_segmentation_sensitivity": _metric(
        "Era segmentation sensitivity",
        "Which proposed boundaries persist when reasonable modeling choices change?",
        "A condition matrix records the dynamic-programming partition starts and compares each partition with the primary nine-segment condition across cluster counts, minimum lengths, grid offsets, weighting, terminal coverage, feature omissions, and common genre.",
        "A boundary supported under most comparable conditions is robust within this specification space, not historically inevitable.",
        ["Build four-year cycle fingerprints", "Standardize the retained feature axes",
         "Minimize within-segment squared distance under each declared condition", "Compare starts, support, objective, and partition similarity"],
        "argmin partition Σ within-segment squared distance",
        "boundary support, objective, and adjusted Rand similarity",
        "Results depend on the declared feature system and condition grid; the incomplete terminal cycle is explicitly right-censored.",
        "era_boundaries/sensitivity.parquet + era_boundaries/meta.json",
        "derived sensitivity analysis",
    ),
}


# Public glossary order.  Keeping this outside the page renderer makes the
# analytical question—not dictionary insertion order—the navigation contract.
METRIC_GROUPS: tuple[tuple[str, str, tuple[str, ...]], ...] = (
    (
        "attention",
        "Attention, topics, and continuity",
        (
            "effective_topics",
            "depth_words",
            "leading_topic_share",
            "adjacent_similarity",
            "paragraph_share",
            "legacy_issue_attention",
            "topic_lifecycle",
            "actual_speaker_topic_presence",
            "actual_speaker_topic_contribution",
        ),
    ),
    (
        "language",
        "Language, form, and temporal framing",
        (
            "rate_10k",
            "explore_centered_lexical_rate",
            "reading_level",
            "primary_medium",
            "assigned_audience",
            "proposal_values",
            "temporal_orientation",
            "temporal_portrait",
            "hope_doom_ratio",
            "legal_procedural",
            "legal_hype_ratio",
            "hype_doom",
            "coarse_pos_share",
        ),
    ),
    (
        "entities",
        "People, institutions, conflict, and networks",
        (
            "era_distinctive_reference",
            "reference_type_presence",
            "actual_speaker_invocation_paragraph_count",
            "enemy_identity",
            "enemy_category_share",
            "network_edge",
            "similarity",
        ),
    ),
    (
        "data-trust",
        "Data trust, reproducibility, and periodization",
        (
            "annotation_population_lineage",
            "annotation_evidence_visibility",
            "annotation_pipeline_lineage",
            "annotation_processing_completion",
            "intermodel_agreement_overall",
            "intermodel_agreement_by_story_era",
            "entity_name_and_stance_reproducibility",
            "exact_agreement",
            "jaccard",
            "era_annual_abruptness",
            "era_segmentation_sensitivity",
        ),
    ),
    (
        "comparison",
        "Comparison and uncertainty",
        (
            "president_percentile",
            "era_relative",
            "confidence_interval",
            "uncertainty_envelope",
            "p_value",
            "kappa",
        ),
    ),
)


def validate_metric_groups() -> None:
    """Require every public measure to appear in one glossary group exactly once."""
    grouped = [name for _, _, names in METRIC_GROUPS for name in names]
    duplicates = sorted({name for name in grouped if grouped.count(name) > 1})
    missing = sorted(set(METRICS) - set(grouped))
    unknown = sorted(set(grouped) - set(METRICS))
    if duplicates or missing or unknown:
        raise ValueError(
            "invalid metric groups: "
            f"duplicates={duplicates}, missing={missing}, unknown={unknown}"
        )


validate_metric_groups()

CHART_METRICS = {
    "institution_grows": {"effective_topics"},
    "certainty": {"rate_10k"}, "hypedoom": {"hype_doom", "rate_10k"},
    "quadrant": {"hype_doom", "legal_procedural"}, "hopefear": {"rate_10k"},
    "readability": {"reading_level"}, "issues": {"uncertainty_envelope"},
    "llm_topics": {"paragraph_share"}, "keywords": {"rate_10k"},
    "progressive_crises": {"paragraph_share"}, "new_deal": {"paragraph_share"},
    "kinship_radar": {"similarity"},
    "map": {"similarity"}, "heatmap": {"similarity"},
    "families": {"rate_10k"}, "naming": {"rate_10k"},
    "written_republic": {"primary_medium", "legal_procedural"},
    "written_full": {"primary_medium", "legal_procedural"},
    "expansion_story": {"paragraph_share", "confidence_interval"},
    "fear_early": {"rate_10k"}, "fear_full": {"rate_10k"},
    "fear_index_era": {"rate_10k"}, "fear_index_full": {"rate_10k"},
    "civil_rights_crisis": {"paragraph_share"},
    "civil_rights_yearly": {"paragraph_share"},
    "civil_rights_full": {"paragraph_share", "confidence_interval"},
    "procedural_gilded": {"legal_procedural", "hype_doom"},
    "procedural_later": {"legal_procedural", "hype_doom"},
    "procedural_present": {"legal_procedural", "hype_doom"},
    "procedural_eras": {"legal_procedural", "hype_doom"},
    "summary_register_timeline": {"legal_hype_ratio", "rate_10k", "legal_procedural", "hype_doom"},
    "progressive_1": {"paragraph_share"}, "progressive_2": {"paragraph_share"},
    "progressive_3": {"paragraph_share"}, "progressive_4": {"paragraph_share"},
    "progressive_heatmap": {"paragraph_share"},
    "naming_progressive": {"rate_10k"},
    "summary_modals": {"rate_10k"},
    "summary_pronouns": {"rate_10k"},
    "broadcast": {"primary_medium", "reading_level"},
    "platform_signals": {"rate_10k", "hype_doom", "legal_procedural"},
    "platform_era": {"rate_10k", "hype_doom", "legal_procedural"},
    "platform_full": {"rate_10k", "hype_doom", "legal_procedural"},
    "weather_map": {"rate_10k", "hype_doom"},
    "summary_audience": {"assigned_audience"},
    "summary_medium": {"primary_medium"},
    "summary_conflict_targets": {"enemy_category_share"},
    "summary_conflict_frame_portraits": {"enemy_identity", "paragraph_share"},
    "summary_temporal": {"temporal_portrait", "rate_10k"},
    "summary_temporal_timeline": {"temporal_portrait", "rate_10k"},
    "summary_hope_doom_ratio": {"hope_doom_ratio", "hype_doom", "rate_10k"},
    "summary_topic_relationships": {"actual_speaker_topic_presence"},
    "profile_topic_ego": {"actual_speaker_topic_presence"},
    "profile_invocation_bars": {"actual_speaker_invocation_paragraph_count"},
    "era_reference_landscape": {"reference_type_presence"},
    "compare_rhetoric_corpus": {"president_percentile", "rate_10k", "reading_level"},
    "compare_rhetoric_ai": {"president_percentile", "paragraph_share", "proposal_values", "effective_topics"},
    "compare_agenda_broad": {"actual_speaker_topic_presence"},
    "explore_lexical_trends": {"explore_centered_lexical_rate"},
    "explore_corex_trends": {"paragraph_share", "confidence_interval"},
    "explore_ai_topic_trends": {"paragraph_share", "uncertainty_envelope"},
}


def validate_metric_names(names: set[str]) -> None:
    missing = names - set(METRICS)
    if missing:
        raise ValueError(f"substantive metrics missing registry definitions: {sorted(missing)}")


def validate_charts(chart_names: set[str]) -> None:
    missing = chart_names - set(CHART_METRICS)
    if missing:
        raise ValueError(f"substantive charts lack registered metrics: {sorted(missing)}")
    validate_metric_names(set().union(*(CHART_METRICS[name] for name in chart_names)))


def lesson_html(metric_name: str) -> str:
    metric = METRICS[metric_name]
    steps = "".join(f"<li>{escape(step)}</li>" for step in metric["steps"])
    return (
        f'<details class="metric-lesson"><summary>Explain this measure</summary>'
        f'<p><strong>{escape(metric["label"])}</strong> — {escape(metric["definition"])}</p>'
        f'<p class="toy">{escape(metric["example"])}</p><ol>{steps}</ol>'
        f'<details><summary>Formula and limitations</summary>'
        f'<p><code>{escape(metric["formula"])}</code> · {escape(metric["unit"])}</p>'
        f'<p>{escape(metric["limitations"])}</p></details></details>'
    )


def measure_tile_html(metric_name: str, label: str | None = None) -> str:
    """Compact, single-level measure disclosure for Story Page V3 charts."""
    metric = METRICS[metric_name]
    steps = "".join(f"<li>{escape(step)}</li>" for step in metric["steps"])
    visible_label = label or metric["label"]
    return (
        '<details class="inspector-tile measure-tile">'
        f'<summary><span aria-hidden="true">∑</span> Measure · '
        f'{escape(visible_label)}</summary>'
        f'<div class="inspector-panel"><p><strong>Definition.</strong> '
        f'{escape(metric["definition"])}</p>'
        f'<p><strong>Unit.</strong> {escape(metric["unit"])}.</p>'
        f'<p><strong>Calculation.</strong></p><ol>{steps}</ol>'
        f'<p><strong>Example.</strong> {escape(metric["example"])}</p>'
        f'<p><strong>Limitation.</strong> {escape(metric["limitations"])}</p>'
        f'<p><code>{escape(metric["formula"])}</code></p></div></details>'
    )
